### PR TITLE
Add more ports to the rules, use remoteports for outbound rule

### PR DESCRIPTION
**Pull request by jacklul**
Tested and working.
Blocks in lobbies that are not using primary port, side effect: your social club status might go to offline.

https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby/issues/6

_Need to be compiled and commited to the repo_

### CODE REVIEW

**Comment by CodeSwine** [comment]
Hi @jacklul ,

Apologies for my absence. 

I don't have GTA installed a.t.m. so I can't really test your pull request. You've mentioned that the user their social club status might appear offline. Is it still possible to invite your friends when you're in-game?

I know many probably use this to play alone, but some also use this to play with their friends in private.

Kind regards,
CodeSwine

**Comment by jacklul** [comment]
> Hi @jacklul ,
> 
> Apologies for my absence.
> 
> I don't have GTA installed a.t.m. so I can't really test your pull request. You've mentioned that the user their social club status might appear offline. Is it still possible to invite your friends when you're in-game?
> 
> I know many probably use this to play alone, but some also use this to play with their friends in private.
> 
> Kind regards,
> CodeSwine

Unfurtunately you can't invite offline person, I would actually go and close this PR and request some kind of switch for this - so that user can decide about this.
The extended ports method works in lobbies where blocking that one port doesn't seem to work.

I actually did a private build where I have those two modes implemented under different buttons and hotkeys and also added suspending hotkey/button for 'gta5.exe' process using external 'pssuspend' program.

In practice it's way more efficient to join GTAO, suspend process for 10 seconds then unsuspend it and enable rules, it works perfectly and just using the rules sometimes leads to total disconnect and being put back to single player.

Take a look at https://github.com/jacklul/GTA5Online-Private_Public_Lobby/tree/private
pssuspend is in PsTools package: https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend

It's not a great code, this was my first touch into C#.

**Comment by CodeSwine** [comment]
Hi @jacklul 

I took a quick look at your code and understand what you're trying to achieve. I agree that your process is efficient and effective. However, I am not too sure about the user-friendliness of this implementation. I want to keep this application really simple. 

I'll take a look at the blocked ports and might exclude the one that makes yourself appear offline and might add an advanced menu for the more experienced users among us. 

I'll keep you updated.

Kind Regards
CodeSwine

**Comment by Column01** [comment]
Hey @CodeSwine 
Have you had the chance to test this PR?

**Comment by Elec0** [comment]
@jacklul I'm going to close this PR since it should have a switch for the feature. If you want to make sure your suspend and switch is up to snuff I'd be willing to give that a test.

**Pull request closed without merging**
